import JSZip from "jszip";
import { buildDeployScript, NETWORK_CONFIG } from "@/lib/deploy-script";

function extractConstructorParams(code: string): string {
  const match = code.match(/constructor\s*\(([^)]*)\)/);
  return match ? match[1].trim() : "";
}

function extractSolidityVersion(code: string): string {
  const match = code.match(/pragma solidity\s+([^;]+);/);
  if (!match) return "0.8.24";
  const versionMatch = match[1].match(/(\d+\.\d+\.\d+)/);
  return versionMatch ? versionMatch[1] : "0.8.24";
}

function toPackageName(contractName: string) {
  const kebab = contractName
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .toLowerCase()
    .replace(/[^a-z0-9-]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
  return kebab || "avalanche-contract";
}

function hardhatConfig(version: string) {
  return `import { HardhatUserConfig } from "hardhat/config";
import "@nomicfoundation/hardhat-toolbox";
import * as dotenv from "dotenv";
dotenv.config();

const config: HardhatUserConfig = {
  solidity: "${version}",
  networks: {
    fuji: {
      url: "${NETWORK_CONFIG.fuji.rpcUrl}",
      chainId: ${NETWORK_CONFIG.fuji.chainId},
      accounts: process.env.PRIVATE_KEY ? [process.env.PRIVATE_KEY] : [],
    },
    avalanche: {
      url: "${NETWORK_CONFIG["avalanche-mainnet"].rpcUrl}",
      chainId: ${NETWORK_CONFIG["avalanche-mainnet"].chainId},
      accounts: process.env.PRIVATE_KEY ? [process.env.PRIVATE_KEY] : [],
    },
  },
};

export default config;
`;
}

function packageJson(name: string) {
  return JSON.stringify(
    {
      name,
      version: "1.0.0",
      private: true,
      scripts: {
        compile: "hardhat compile",
        "deploy:fuji": "hardhat run scripts/deploy.ts --network fuji",
        "deploy:mainnet": "hardhat run scripts/deploy.ts --network avalanche",
      },
      devDependencies: {
        "@nomicfoundation/hardhat-toolbox": "^5.0.0",
        hardhat: "^2.22.0",
        dotenv: "^16.4.0",
        typescript: "^5.5.0",
      },
      dependencies: {
        "@openzeppelin/contracts": "^5.0.0",
      },
    },
    null,
    2
  );
}

function envExample() {
  return `# Private key of the wallet that will deploy the contract.
# Get testnet AVAX from https://core.app/tools/testnet-faucet/
# NEVER commit this file with a real key filled in.
PRIVATE_KEY=
`;
}

function readme(contractName: string, constructorNote: string) {
  return `# ${contractName}

Generated by Avalanche AI Flow Builder — a ready-to-run Hardhat project
for this contract.

## Setup

\`\`\`bash
npm install
cp .env.example .env
# edit .env and set PRIVATE_KEY to a wallet funded with testnet AVAX
\`\`\`

## Compile

\`\`\`bash
npx hardhat compile
\`\`\`
${constructorNote}
## Deploy to Avalanche Fuji testnet

\`\`\`bash
npx hardhat run scripts/deploy.ts --network fuji
\`\`\`

Get testnet AVAX from the [Core faucet](https://core.app/tools/testnet-faucet/)
before deploying.

## Deploy to Avalanche C-Chain mainnet

\`\`\`bash
npx hardhat run scripts/deploy.ts --network avalanche
\`\`\`

**This spends real AVAX. Double-check your contract and constructor
arguments first.**
`;
}

function gitignore() {
  return `node_modules
.env
artifacts
cache
typechain-types
`;
}

export interface ExportProjectInput {
  code: string;
  contractName: string;
  constructorArgs?: string;
}

export async function exportProjectZip({
  code,
  contractName,
  constructorArgs,
}: ExportProjectInput): Promise<Blob> {
  const name = contractName?.trim() || "MyContract";
  const version = extractSolidityVersion(code);
  const { deployScript } = buildDeployScript({
    contractName: name,
    network: "fuji",
    constructorArgs,
  });

  const zip = new JSZip();
  zip.file(`contracts/${name}.sol`, code);
  zip.file("scripts/deploy.ts", deployScript);
  zip.file("hardhat.config.ts", hardhatConfig(version));
  zip.file("package.json", packageJson(toPackageName(name)));
  zip.file(".env.example", envExample());
  zip.file(".gitignore", gitignore());

  const constructorParams = extractConstructorParams(code);
  const constructorNote =
    constructorParams && !constructorArgs?.trim()
      ? `\n**This contract's constructor takes arguments** (\`${constructorParams}\`) — open \`scripts/deploy.ts\` and fill them into the \`.deploy(...)\` call before running it, or the deploy will fail.\n`
      : "";
  zip.file("README.md", readme(name, constructorNote));

  return zip.generateAsync({ type: "blob" });
}

export function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
